title: GravTrade
description: Best forex broker, lowest spread broker, low commission broker, ECN broker, best trading platform, bonus, rebate
author: GravTrade
logo: /static/img/gravtrade-forex-trading-large-logo-white.png
github: http://www.gravtrade.com
about: Research | Analyse | Execute

baseurl: "http://www.gravtrade.com"
url: "http://www.gravtrade.com"

disqus_shortname: GravTrade
google_analytics: UA-83911096-1

share:
  twitter_username: GravTrade
  fb_appid: 146485415802294


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist,jekyll-sitemap]

jekyll_repo: 
  source_dir: https://github.com/gravtrade/JekyllMail
  pop_server: pop.gmail.com
  pop_user: h798506@gmail.com
  pop_password: Mqy9kn7p
  secret: 1234
  markup: markdown
  site_url: http://www.gravtrade.com
  commit_after_save: true
