title: GravTrade
description: Forex broker, lowest spread and commission, ECN DMA STP account type, best signal provider, trading strategy and trading platform API comparison.
author: GravTrade
logo: /static/img/avatar.png
github: https://github.com/ashutosh2k12
about: For Successful Trader

baseurl: ""
url: "http://www.gravtrade.com/"

disqus_shortname: GravTrade
google_analytics: UA-83911096-1

share:
  twitter_username: \#
  fb_appid: 146485415802294


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
